theme: jekyll-theme-cayman
title: "'Geospatial Programming using ArcPy' Class Projects"
description: "This is the class project page showcasing the Geospatial Programing Class of Spring of 2020, a collaboration between the universities of EPF and RUDN"
github:
  is_project_page: false
